ANSWERS/djangoanswers/dogs/dogs/urls.py
"""dogs URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  path('view_name', views.view_name, name='view_name')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  path('view_name', ViewName.as_view(), name='view_name')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.urls import url, include
    2. Add a URL to urlpatterns:  path('appname', include('app.urls', namespace="app"))
    Path may be blank; in that case only the app URL is used

    -----------------------------------------------------------------------------------
    NOTE: when using the namespace argument with include(), the app's urls.py MUST have

        app_name="APPNAME"

    before  urlpatterns = ...
    -----------------------------------------------------------------------------------
"""
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

# site-wide route mapping
urlpatterns = [
    path('admin', admin.site.urls),
    # To include urls from an app:
    #
    # path('', include('app.urls', namespace="appname")),  # delegate to app's URL config
    #
    # note: if path (1st arg) is not empty, it will be a prefix to app URL
    # and will follow the hostname, before the path in the app's urls.py
    #
    # i.e., if path here is "spam" and path in app/urls.py is "home",
    # url will be HOSTNAME:PORT/spam/home
    #
    # if first arg is empty, then paths in app.urls will immediately follow
    #  the host name

    # To configure a single view:
    #
    # from app.views import myview
    # path('viewpath', myview, name="myview")
    path('', include('dogs_core.urls', namespace="dogs_core")),  # delegate to app's URL config
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

# include Django Debug toolbar if DEBUG is set
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

ANSWERS/djangoanswers/dogs/dogs_core/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
from . import viewsets

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'dogs', viewsets.DogsViewSet)
router.register(r'breeds', viewsets.BreedsViewSet)


urlpatterns = [
    # add the paths that are automatically generated by the
    # viewsets
    path('', include(router.urls)),

    # add path for function-based API view
    path('fbv/dogs', views.dogs, name="fbdogs"),

    # add paths for class-based API views
    # each model has two views, corresponding to
    # *resources* -- one with the primary key, and one
    # without

    # used with GET, provides list of Dog resources
    # used with POST, creates new resource
    path('cbv/dogs', views.DogsList.as_view(), name="dogs-cbv"),

    # used with GET, retrieves one Dog resource
    # used with PUT, replaces a Dog resource
    # used with PATCH, updates a Dog resource
    # used with DELETE, deletes a Dog resource
    path('cbv/dogs/<str:pk>', views.DogsDetail.as_view(), name="dogs-detail-cbv"),

    # same idea for Breed resources
    path('cbv/breeds', views.BreedsList.as_view(), name="breeds-cbv"),
    path('cbv/breeds/<str:pk>', views.BreedsDetail.as_view(), name="breeds-detail-cbv"),
]

ANSWERS/djangoanswers/dogs/dogs_core/urls.py
"""
URL Configuration for dogs_core
"""
from django.urls import path, include
from . import views

app_name = 'dogs_core'

urlpatterns = [
    # routes for web pages (not API)

    # home page
    path('', views.home, name="home"),

    # list all objects
    path('dogs', views.DogListView.as_view(), name="dogs"),
    path('breeds', views.BreedListView.as_view(), name="breeds"),

    # list details for an object
    path('dog/<str:pk>', views.DogDetailView.as_view(), name="dog"),

    path('breed/<str:pk>', views.BreedDetailView.as_view(), name="breed"),

    # list dogs by sex (and optional name)
    path('by_sex/<str:sex>', views.by_sex, name="by_sex"),

    # get shortest name
    path('shortest', views.shortest, name='shortest'),

    # alternate dog list using template with 'fancy' filter
    path('fancy_list', views.DogListViewFancy.as_view(), name='fancy_list'),

    # use the "fancy" view and template that uses a
    # custom filter
    path(
        'fancy_detail/<str:pk>',
        views.DogDetailViewFancy.as_view(),
        name='fancy_detail'
    ),

    path('dogs_include', views.dogs_include, name='dogs_include'),

    # routes for the API (delegated to dogs_core.api.urls)

    path('api/', include('dogs_core.api.urls', namespace="api")),
]

ANSWERS/djangoanswers/dogs/dogs_core/models.py
import uuid
from django.db import models

# define a model, which is the core of the Django app
# a model corresponds to a DB table
class Breed(models.Model):
    # specify model fields; these correspond to table columns
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, help_text="Unique ID of this artist")
    abbr = models.CharField(max_length=4, null=True, help_text="Abbreviation of breed name")

    name = models.CharField(max_length=64, help_text="Name of breed")

    # specify metadata for this model.
    class Meta:
        # set table name, otherwise defaults to
        #  APP_NAME_MODEL
        db_table = 'breeds'

    def __str__(self):
        return self.name

class DogManager(models.Manager):
    """
    Custom manager for the Dog model.

    This custom manager will add an aggregate function to
    return the dog with the shortest name
    """
    def __init__(self):
        super().__init__()

    def shortest_name(self):
        dogs = Dog.objects.all().order_by('name')
        return dogs.first()


class Dog(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, help_text="Unique ID of this artist")
    name = models.CharField(max_length=64, help_text="Name of dog")
    sex = models.CharField(max_length=1, choices=[('f', 'Female'), ('m', 'Male')], help_text="Sex of dog (m or f)")
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, related_name="breeds", help_text="Breed of dog")
    is_neutered = models.BooleanField(default=False, help_text="Whether dog is neutered")
    weight  = models.IntegerField(help_text="Approximate weight of dog in pounds")
    bites = models.BooleanField(default=False,
                                help_text="Whether dog bites")

    objects = DogManager()

    class Meta:
        db_table = 'dogs'
        # sort Dog objects by the 'name' field
        # on the related field 'breed'
        # if you just order by 'breed', it will order
        # by the breed ID, not the name
        ordering = ['breed__name', 'name']

    def __str__(self):
        return f"{self.name} ({self.breed})"

    def save(self, *args, **kwargs):
        print("Woof! Woof!")
        super().save(*args, **kwargs)

ANSWERS/djangoanswers/dogs/dogs_core/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer

# import models
from dogs_core.models import Dog, Breed

# import generic class-based views
from rest_framework import generics

# import custom serializers
from  .serializers import DogSerializerX, DogSerializer, BreedSerializer

# function-based view to respond to GET request on Dog resource
@api_view(['GET'])
def dogs(request):
     dogs = Dog.objects.all() # get all records
     serializer = DogSerializerX(dogs, many=True) # serialize the records
     dogs_json = JSONRenderer().render(serializer.data)  # create JSON version of data
     return Response(dogs_json, 200)  # return JSON to client


# class-based views (aka CBVs)

# handle GET or POST requests without PK
class DogsList(generics.ListCreateAPIView):
    queryset = Dog.objects.all()
    serializer_class = DogSerializer

# handle GET, POST, PUT, PATCH, DELETE requests with PK
class DogsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Dog.objects.all()
    serializer_class = DogSerializer

class BreedsList(generics.ListCreateAPIView):
    queryset = Breed.objects.all()
    serializer_class = BreedSerializer

class BreedsDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Breed.objects.all()
    serializer_class = BreedSerializer

ANSWERS/djangoanswers/dogs/dogs_core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.db.models import Q

from .models import *

def home(request):
    return render(request, 'dogs_core/home.html', {
        'message': "Welcome to the Dogs",
        'home': True,
    })

# use generic view to handle displaying all objects
class DogListView(ListView):
    # this view uses template dog_list.html
    # use "template=..." to specify a different template
    model = Dog
    context_object_name = "dogs"

# use generic view to handle displaying a single object
# this view uses template dog_detail.html
class DogDetailView(DetailView):
    model = Dog
    context_object_name = 'dog'
    # note: could add a filter here to handle
    #  ?name=value&name=value parameters on the URL

class DogCreateView(CreateView):
    model = Dog
    fields = ['id', 'name', 'breed', 'is_neutered',
              'bites', 'weight', 'sex']


class DogListViewFancy(ListView):
    model = Dog
    context_object_name = "dogs"
    template_name = 'dogs_core/dog_list_fancy.html'


class DogDetailViewFancy(DetailView):
    """
    This view will use a template that incorporates
    the custom 'fancy' filter
    """
    model = Dog
    context_object_name = 'dog'
    template_name = 'dogs_core/dog_detail_fancy.html'


class BreedListView(ListView):
    # this view uses template breed_list.html
    model = Breed
    context_object_name = "breeds"


class BreedDetailView(DetailView):
    # this view uses template breed_detail.html
    model = Breed
    context_object_name = 'breed'

class BreedCreateView(CreateView):
    model = Breed
    fields = ['id', 'name', 'abbr']


def by_sex(request, sex):
    """
    Request a list of dogs by sex
    :param sex: 'm' or 'f'
    the sex parameter is part of the url
     for example:
      .../by_sex/m

    the name parameter is a GET request parameter
    which comes after the ? in the URL
    for example:
      .../by_sex/f/n
    """

    # check GET parameter from URL (after '?' in URL)
    name = request.GET.get('name')

    # add query for sex
    queries = [Q(sex=sex)]

    # if ?name=xxx is supplied on URL,
    # add name query
    if name:
        queries.append(Q(name__istartswith=name))

    # filter dogs with optional name query
    dogs = Dog.objects.filter(*queries)
    return render(request, 'dogs_core/dog_list.html', {
        'dogs': dogs,
    })

def shortest(request):
    """
    Return the shortest dog name in the db.

    This uses an aggregate method on a custom manager
    (see dogs_core.models)

    :param request: HTTP request
    :return: HTML page
    """
    shortest_name = Dog.objects.shortest_name()
    return render(request, 'dogs_core/shortest.html', {
        'shortest_name': shortest_name,
    })

def dogs_include(request):
    """
    Use template containing {% include ... %} directive
    """
    dogs = Dog.objects.all()
    return render(request, 'dogs_core/dogs_include.html', {
        'dogs': dogs,
    })

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/breed_detail.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
    <h2>{{ breed.name }}</h2>
    <h3>Short name: {{ breed.abbr }}</h3>
        <br/>

    <a href="{% url 'dogs_core:breeds' %}">Return to Breed page</a>
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/breed_list.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
    <h1>Breeds</h1>
    <table>
    {% for breed in breeds %}
        <tr><td><a href="{% url 'dogs_core:breed' breed.id %}">{{ breed.name }}</a></td>
    {% endfor %}
    </table>
        <br/>

</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dog_detail.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
    <h2>{{ dog.name }} ({{ dog.breed }})</h2>
    <h3>Sex: {{ dog.sex }}</h3>
    <h3>Is neutered: {{ dog.is_neutered }}</h3>
    <h3>Weight: {{ dog.weight }}</h3>
    <h3>Bites: {{ dog.bites }}</h3>
    <br/>
    <a href="{% url 'dogs_core:dogs' %}">Return to Dogs page</a>
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dog_detail_fancy.html
{% extends "dogs_core/dogs_core_base.html" %}
{% load custom_filters %}
{% block content %}
<div class="container">
    <h2>{{ dog | fancy}})</h2>
    <h3>Sex: {{ dog.sex }}</h3>
    <h3>Is neutered: {{ dog.is_neutered }}</h3>
    <h3>Weight: {{ dog.weight }}</h3>
    <h3>Bites: {{ dog.bites }}</h3>
    <br/>
    <a href="{% url 'dogs_core:fancy_list' %}">Return to Dogs (Fancy) page</a>
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dog_list.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
    <h1>Dogs</h1>
    <table>
        <tr><th>Name</th><th>Breed</th>
    {% for dog in dogs %}
        <tr><td><a href="{% url 'dogs_core:dog' dog.id %}">{{ dog.name }}</a></td> <td>{{ dog.breed }}</td>
    {% endfor %}
    </table>
        <br/>
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dog_list_fancy.html
{% extends "dogs_core/dogs_core_base.html" %}
{% load custom_filters %}
{% block content %}
<div class="container">
    <h1>Dogs</h1>
    {% for dog in dogs %}
        <a href="{% url 'dogs_core:fancy_detail' dog.id %}">{{ dog | fancy }}</a><br/>
    {% endfor %}
        <br/>
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dogs_core_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}dogs_core{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% endblock css %}

  </head>

  <body>

    <div class="container">

      {% block header %}{% endblock header %}
      {% block content %}
        <p>Default content for dogs_core</p>
      {% endblock content %}

      <!--
      add a link to every page to return to the home page,
      unless we're actually on the home page

      IRL this would  probably be an image of the site's logo
      or something similar
      -->
      {% if not home %}
      <br/>

      <a href="{% url 'dogs_core:home' %}">Return to Home page</a>
      {% endif %}


      {% block footer %}{% endblock footer %}

    </div> <!-- /container -->

    <!-- Javascript Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Third-party javascript libraries go here -->

      <!-- App-specific Javascript in this file -->

      <script src="{% static 'js/dogs_core.js' %}"></script>


    {% endblock javascript %}

  </body>
</html>

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dogs_include.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
{% include "dogs_core/dogs_ordered_list.html" %}
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/dogs_ordered_list.html
<div class="container">
    <ol>
    {% for dog in dogs %}
        <li>{{ dog.name }}</li>
    {% endfor %}
    </ol>
</div>

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/home.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
    <h1>{{ message }}</h1>

    <a href="{% url 'dogs_core:dogs' %}">Dog List</a> <br/>
    <a href="{% url 'dogs_core:breeds' %}">Breed List</a> <br/>
    <a href="{% url 'dogs_core:fancy_list' %}">Fancy List</a> <br/>
    <a href="{% url 'dogs_core:dogs_include' %}">Template with Include</a>  <br/>
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/sample.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
Sample content for dogs_core
</div>
{% endblock content %}

ANSWERS/djangoanswers/dogs/dogs_core/templates/dogs_core/shortest.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
Shortest name: {{ shortest_name }}
</div>
<a href="{% url 'dogs_core:home' %}">Return to home page</a>

{% endblock content %}