EXAMPLES/djangoexamples/djclass/djclass/urls.py
""" URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  path('view_name', views.view_name, name='view_name')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  path('view_name', ViewName.as_view(), name='view_name')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.urls import path, include
    2. Add a URL to urlpatterns:  path('appname', include('app.urls', namespace="app"))
    Path may be blank; in that case only the app URL is used
"""
from django.conf import settings
from django.urls import path, include
from django.contrib import admin
from django import VERSION

# site-wide route mapping
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('superheroes.urls', namespace="superheroes")),
]

# include Django Debug toolbar if DEBUG is set
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

EXAMPLES/djangoexamples/djclass/superheroes/urls.py
"""
URL Configuration for superheroes
"""
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "superheroes"

urlpatterns = [
    # welcome page using template view
    path('', views.HomeView.as_view(), name='home'),

    path('hello', views.HelloView.as_view(), name='hello'),

    path('another', views.AnotherView.as_view(), name='another'),

    # NO view -- don't do this:
    path(
        'noview',
        TemplateView.as_view(template_name='noview.html'),
        name="noview",
    ),

    # minimal views with models
    path(
        'herolist/',
        views.HeroListView.as_view(),
        name="herolist",
    ),
    path(
        'herodetails/<int:pk>',
        views.HeroDetailView.as_view(),
        name="herodetails",
    ),

    # enhanced views with extra information
    path(
        'herolistplus/',
        views.HeroListViewPlus.as_view(),
        name="herolistplus",
    ),
    path(
        'herodetailsplus/<int:pk>/',
        views.HeroDetailViewPlus.as_view(),
        name="herodetailsplus",
    ),

    # create and update views
    path(
        'herocreate/',
        views.HeroCreateView.as_view(),
        name="herocreate",
    ),
    path(
        'heroupdate/<int:pk>/',
        views.HeroUpdateView.as_view(),
        name="heroupdate",
    ),
    path(
        'success', views.SuccessView.as_view(), name="success",
    )
]

EXAMPLES/djangoexamples/djclass/superheroes/models.py
from django.db import models
import logging

logging.basicConfig(
    filename='superheroes.log',
    level=logging.INFO,
)

class SuperheroManager(models.Manager):
    def get_fliers(self):
        return self.filter(powers__name__icontains="fly")

class Power(models.Model):
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=512)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Enemy(models.Model):
    name = models.CharField(max_length=32)
    powers = models.ManyToManyField(Power)

    def __str__(self):
        return self.name

class Superhero(models.Model):
    name = models.CharField(max_length=32)
    real_name = models.CharField(max_length=32)
    secret_identity = models.CharField(max_length=32)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    powers = models.ManyToManyField(Power)
    enemies = models.ManyToManyField(Enemy)
    objects = SuperheroManager()

    def __str__(self):
        return self.name

    class Meta():
        ordering = ['secret_identity']

    def get_brief_enemies(self):
        enemies = [e.name.split()[-1] for e in self.enemies.all()]
        return '/'.join(enemies)

    def save(self, *args, **kwargs):
        logging.info("Created superhero {}".format(self.name))
        super().save(*args, **kwargs)
        # do something else here as needed

EXAMPLES/djangoexamples/djclass/superheroes/views.py
from abc import ABCMeta, abstractmethod, abstractclassmethod
from django.views.generic import (
    TemplateView, ListView, CreateView, DetailView, UpdateView,
    View
)
from django.urls import reverse_lazy
from django.shortcuts import render
from .models import Superhero, City

class MixinBase(metaclass=ABCMeta):

    @classmethod
    def spam(cls):
        pass

    @classmethod
    def ham(cls):
        pass

    @abstractmethod
    def dispatch(self, *args, **kwargs):
        pass

class ToastMixin(MixinBase):
    pass



class MyCustomMixin(View):
    template_name = 'superheroes/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if hasattr(self, 'data'):
            context.update(self.data)
        return context

class HomeView(MyCustomMixin, TemplateView):
    data = {
        'message': 'Welcome to the superheroes app for class-based views',
    }

class AnotherView(MyCustomMixin, TemplateView):
    data = {
        'message': 'And another view with the same template and mixin',
    }


class HelloView(MyCustomMixin, TemplateView):
    data = {
       'message': 'Hello from the Mixin-ified HelloView class'
    }

class HeroListView(MyCustomMixin, ListView):
    model = Superhero
    # template is model.lower() + "_list.html"

class HeroDetailView(DetailView):
    model = Superhero

class HeroListViewPlus(ListView):
    model = Superhero
    context_object_name = 'heroes'
    template_name = 'superheroes/superhero_list_plus.html'

class HeroDetailViewPlus(DetailView):
    model = Superhero
    context_object_name = 'hero'
    template_name = 'superheroes/superhero_detail_plus.html'

class HeroCreateView(CreateView):
    model = Superhero
    fields = ['name', 'real_name', 'secret_identity', 'city']
    success_url = reverse_lazy('superheroes:success')

class CityCreateView(CreateView):
    model = City
    fields = ['name']
    success_url = reverse_lazy('superheroes:success')

class HeroUpdateView(UpdateView):
    model = Superhero
    # template_name = "hero_update.html"
    fields = ['name', 'real_name', 'secret_identity', 'city']
    success_url = reverse_lazy('superheroes:success')

class SuccessView(TemplateView):
    template_name = 'superheroes/success.html'

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/generic_context.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>Welcome to a generic page</h1>

<h3>Rendered by a generic view {{ message }}</h3>
<br/>
<ul>
    {% for fruit in fruits %}
    <li>{{ fruit }}</li>
    {% endfor %}
</ul>


{% endblock %}
<q1>`   </q1>

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/generic_only.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>Welcome to a generic page</h1>

<h3>Rendered by a generic class without any code in views.py</h3>

{% endblock %}
<q1>`   </q1>

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/generic_view.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>Welcome to a generic page</h1>

<h3>Rendered by a generic view class with minimal code in views.py</h3>

{% endblock %}
<q1>`   </q1>

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/hero_details.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity }}</h2>
<h2>Real Name: {{ hero.real_name }}</h2>
<h3>Powers: {{ hero.powers.all | join:", "}}</h3>
<h3>Enemies: {{ hero.enemies.all | join:", " }}</h3>

<a href="{% url 'superheroes:genericlist' %}">Return to list</a>

{% endblock %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/hero_list.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>Pick a hero:</h1>

{% for hero in heroes %}
<h3><a
  href="{% url 'superheroes:genericdetail' hero.id %}">
    {{ hero.name }}
</a>
    {{ hero.secret_identity }}
</h3>
{% endfor %}

{% endblock %}

</body>
</html>

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/home.html
{% extends "superheroes/superheroes_base.html" %}
{% block content %}
<div class="container">
{{ message }}
</div>
{% endblock content %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/noview.html
{% extends "superheroes/superheroes_base.html" %}
{% block content %}
<div class="container">
DON'T DO THIS!
</div>
{% endblock content %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/success.html
{% extends "superheroes/superheroes_base.html" %}
{% block content %}
<div class="container">
You have successfully created/updated the record
</div>

<div class="container">
<a href="{% url 'superheroes:herolistplus' %}">Return to list</a>
</div>

{% endblock content %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/superhero_detail.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<h2>Secret Identity: {{ object.secret_identity }}</h2>
<h2>Real Name: {{ object.real_name }}</h2>
<h3>Powers: {{ object.powers.all | join:", "}}</h3>
<h3>Enemies: {{ object.enemies.all | join:", " }}</h3>

<a href="{% url 'superheroes:herolist' %}">Return to list</a>

{% endblock %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/superhero_detail_plus.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity }}</h2>
<h2>Real Name: {{ hero.real_name }}</h2>
<h3>Powers: {{ hero.powers.all | join:", "}}</h3>
<h3>Enemies: {{ hero.enemies.all | join:", " }}</h3>

<a href="{% url 'superheroes:herolistplus' %}">Return to list</a>

{% endblock %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/superhero_form.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/superhero_list.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>Pick a hero:</h1>
<h2>(minimal class-based list view)</h2>

{% for hero in object_list %}
<h3><a
  href="{% url 'superheroes:herodetails' hero.id %}">
    {{ hero.name }}
</a>
    {{ hero.secret_identity }}
</h3>
{% endfor %}

{% endblock %}

</body>
</html>

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/superhero_list_plus.html
{% extends "superheroes/superheroes_base.html" %}

{% block content %}

<h1>Pick a hero:</h1>
<h2>(enhanced class-based list view)</h2>

{% for hero in heroes %}
<h3><a
  href="{% url 'superheroes:herodetailsplus' hero.id %}">
    {{ hero.name }}
</a>
    {{ hero.secret_identity }}
</h3>
{% endfor %}

{% endblock %}

</body>
</html>

EXAMPLES/djangoexamples/djclass/superheroes/templates/superheroes/superheroes_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}superheroes{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% endblock css %}

  </head>

  <body>

    <div class="container">

      {% block header %}{% endblock header %}
      {% block content %}
        <p>Default content for superheroes</p>
      {% endblock content %}
      {% block footer %}{% endblock footer %}

    </div> <!-- /container -->

    <!-- Javascript Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Third-party javascript libraries go here -->

      <!-- App-specific Javascript in this file -->

      <script src="{% static 'js/superheroes.js'"></script>


    {% endblock javascript %}

  </body>
</html>